export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
export const FILTER_BY_EXISTENCE = "FILTER_BY_EXISTENCE";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const ORDER_BY_NAME = "ORDER_BY_NAME"

